on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - run: sam build --use-container
        working-directory: dq5-sam-app-1
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name dq5-sam-app-1-stack --s3-bucket dq5-sam-app-1-bucket --region ap-southeast-2
        working-directory: dq5-sam-app-1